### ISSUE TITLE
Importing The CSV into MongoDB

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-10#1]
Hi all,

I am having trouble getting the aid data to import for the MongoDB challenge. Below is a screen shot of my terminal. After looking at the documentation for mongoimport, I am trying to run this command: 

> mongoimport -d test -c aiddata --file aiddata2_1_since_1996.csv --type csv

and I keep getting syntax errors:

![image](https://cloud.githubusercontent.com/assets/8551620/4837957/b7eeb41a-5fe0-11e4-9b07-26d8394d0e25.png)

Mac users, what command did you run to get this data imported?

**Comment by doubleshow** [comment]
Try running "mongoimport" from the command line (rather than from the mongodb shell. Hope this helps.

**Comment by ghost** [comment]
Silly me. That fixed my issue. Thanks!
